# Generated by Django 5.1.3 on 2024-11-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('quan_tri', 'Quản trị'), ('can_bo_khao_thi', 'Cán bộ khảo thí'), ('giao_vu_khoa', 'Giáo vụ khoa'), ('sinh_vien', 'Sinh viên')], max_length=20)),
            ],
        ),
    ]
