# Generated by Django 5.1.3 on 2024-11-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='de_tai',
            field=models.CharField(default='Chưa có đề tài', max_length=200, verbose_name='Đề tài'),
        ),
        migrations.AddField(
            model_name='user',
            name='giang_vien',
            field=models.CharField(default='Chưa có giảng viên', max_length=100, verbose_name='Giảng viên'),
        ),
        migrations.AddField(
            model_name='user',
            name='ho_ten',
            field=models.CharField(default='Chưa có', max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AddField(
            model_name='user',
            name='ma_lop',
            field=models.CharField(default='Chưa có', max_length=20, verbose_name='Mã lớp'),
        ),
        migrations.AddField(
            model_name='user',
            name='ma_so_sinh_vien',
            field=models.CharField(default='Chưa có', max_length=20, unique=True, verbose_name='Mã số sinh viên'),
        ),
        migrations.AddField(
            model_name='user',
            name='trang_thai',
            field=models.CharField(choices=[('da_dang_ky', 'Đã đăng ký'), ('dang_thuc_hien', 'Đang thực hiện'), ('da_hoan_thanh', 'Đã hoàn thành')], default='Chưa có', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
