# Generated by Django 5.1.3 on 2024-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_password_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trang_thai',
            field=models.CharField(choices=[('Đã đăng ký', 'Đã đăng ký'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chưa có', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
