# Generated by Django 5.1.3 on 2024-11-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_trang_thai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_so_sinh_vien', models.CharField(default='Chưa có', max_length=20, unique=True, verbose_name='Mã số sinh viên')),
                ('ho_ten', models.CharField(default='Chưa có', max_length=100, verbose_name='Họ tên')),
                ('ma_lop', models.CharField(default='Chưa có', max_length=20, verbose_name='Mã lớp')),
                ('de_tai', models.CharField(default='Chưa có đề tài', max_length=200, verbose_name='Đề tài')),
                ('giang_vien', models.CharField(default='Chưa có giảng viên', max_length=100, verbose_name='Giảng viên')),
            ],
        ),
    ]
