# Generated by Django 5.1.3 on 2024-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_advior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advior',
            name='giang_vien',
        ),
        migrations.RemoveField(
            model_name='advior',
            name='ma_lop',
        ),
        migrations.RemoveField(
            model_name='advior',
            name='ma_so_sinh_vien',
        ),
        migrations.AddField(
            model_name='advior',
            name='chuyen_nganh',
            field=models.CharField(default='Chưa có', max_length=20, verbose_name='Chuyên ngành'),
        ),
        migrations.AddField(
            model_name='advior',
            name='tinh_trang',
            field=models.CharField(choices=[('Chưa nhận', 'Chưa nhận'), ('Đã nhận', 'Đã nhận')], default='Chưa có', max_length=30, verbose_name='Tình trạng'),
        ),
    ]
