# Generated by Django 5.1.3 on 2024-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_advior_giang_vien_remove_advior_ma_lop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstudent', models.CharField(max_length=255, verbose_name='MSSV')),
                ('project', models.CharField(max_length=255, verbose_name='Đồ án đề tài')),
                ('diem_lan_1', models.CharField(max_length=255, verbose_name='Điểm lần 1')),
                ('diem_lan_2', models.CharField(max_length=255, verbose_name='Điểm lần 2')),
                ('ghi_chu', models.CharField(max_length=255, verbose_name='Ghi chú')),
            ],
        ),
        migrations.AlterField(
            model_name='advior',
            name='ho_ten',
            field=models.CharField(default='Chưa có', max_length=100, unique=True, verbose_name='Họ tên'),
        ),
    ]
