# Generated by Django 5.1.3 on 2024-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_exam_alter_advior_ho_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advior',
            name='chuyen_nganh',
            field=models.CharField(max_length=20, verbose_name='Chuyên ngành'),
        ),
        migrations.AlterField(
            model_name='advior',
            name='de_tai',
            field=models.CharField(max_length=200, verbose_name='Đề tài'),
        ),
        migrations.AlterField(
            model_name='advior',
            name='ho_ten',
            field=models.CharField(max_length=100, unique=True, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='advior',
            name='tinh_trang',
            field=models.CharField(choices=[('Chưa nhận', 'Chưa nhận'), ('Đã nhận', 'Đã nhận')], max_length=30, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='user',
            name='de_tai',
            field=models.CharField(max_length=200, verbose_name='Đề tài'),
        ),
        migrations.AlterField(
            model_name='user',
            name='giang_vien',
            field=models.CharField(max_length=100, verbose_name='Giảng viên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ho_ten',
            field=models.CharField(max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ma_lop',
            field=models.CharField(max_length=20, verbose_name='Mã lớp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ma_so_sinh_vien',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã số sinh viên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trang_thai',
            field=models.CharField(choices=[('Đã đăng ký', 'Đã đăng ký'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã hoàn thành', 'Đã hoàn thành')], max_length=20, verbose_name='Trạng thái'),
        ),
    ]
