# Generated by Django 5.1.3 on 2024-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_advior_chuyen_nganh_alter_advior_de_tai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='diem_trung_binh',
            field=models.FloatField(default=0.0, verbose_name='Điểm trung bình'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tensv',
            field=models.CharField(default='Chưa cập nhật', max_length=255, verbose_name='Tên sinh viên'),
        ),
    ]
