# Generated by Django 5.1.3 on 2024-12-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_exam_diem_trung_binh_exam_tensv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='diem_lan_1',
            field=models.FloatField(max_length=255, verbose_name='Điểm lần 1'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='diem_lan_2',
            field=models.FloatField(max_length=255, verbose_name='Điểm lần 2'),
        ),
    ]
