# Generated by Django 5.1.3 on 2024-12-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_exam_diem_lan_1_alter_exam_diem_lan_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='tensv',
            field=models.CharField(default='', max_length=255, verbose_name='Họ tên sinh viên'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
