# Generated by Django 5.1.3 on 2024-12-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_advior_ho_ten'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
